#!/bin/bash

file="$SECOND_BRAIN"'/03-Resources/books/'$1.md
echo "$file"
cd "$SECOND_BRAIN" || exit

new_note() {
	touch "$file"

	# Format the file with the daily template
	cat <<EOF >"$file"
---
tags:
  - books
  -
---
# $1

# Which capture criteria?
[ ] Inspiration
[ ] Personal
[ ] Suprising
[ ] Useful

## What is the new idea?

## What was discussed


## Other
EOF

}

# If the daily note does not exist, create a new one.
# this uses the test command with the -f flag.
if [ ! -f "$file" ]; then
	echo "File does not exist, creating new daily note."
	new_note
fi

# Open the daily note at the bottom of the file in insert mode
nvim '+ normal Gzzo' "$file"
# Open the daily note at the bottom of the file in insert mode and run NoNeckPain to make it center
# nvim '+ normal Gzzo' "$file" -c :NoNeckPain
