#!/bin/bash

today=$(date +"%Y-%m-%d-%H-%M")
projectsDir=$("$SECOND_BRAIN"'/01-Projects/')
folder=$(find "$SECOND_BRAIN"'/01-Projects/' -mindepth 1 -maxdepth 3 -type d | fzf --header="Select a directory:")
fileName=$(date +"%Y-%m-%d-%H-%M")'_'$1
file="$folder/"$(date +"%Y-%m-%d")'_'$1'.md'

cd "$folder" || exit

new_note() {
  touch "$file"

  # Format the file with the daily template
  cat <<EOF >"$file"
---
tags:
  - 
  -
---
# $fileName

## Links

## Tracking

EOF
  find "$SECOND_BRAIN/01-Projects/" -mindepth 1 -maxdepth 1 -type d -printf "- [ ] %f\n" >>$file
  cat <<EOF >>"$file"

## Meeting Notes
Present:
- Maatar
- 

## Work Notes

### Next Tasks

## Tasks list


## Other
EOF

}

# If the daily note does not exist, create a new one.
# this uses the test command with the -f flag.
if [ ! -f "$file" ]; then
  echo "File does not exist, creating new daily note."
  new_note
fi

# Open the daily note at the bottom of the file in insert mode
nvim '+ normal Gzzo' "$file"
# Open the daily note at the bottom of the file in insert mode and run NoNeckPain to make it center
# nvim '+ normal Gzzo' "$file" -c :NoNeckPain
